package edu.ucdavis.genomics.metabolomics.binbase.dsl.processable.statistic

import java.sql.Connection;

import org.jdom.Element;

import edu.ucdavis.genomics.metabolomics.binbase.algorythm.data.ResultDataFile;
import edu.ucdavis.genomics.metabolomics.binbase.bdi.math.BinComparisonMatrix;
import edu.ucdavis.genomics.metabolomics.util.statistics.data.DataFile;

/**
 * generate a report for all the bins generated by this experiment and if they are likley duplicates to an existing bin or not
 * @author wohlgemuth
 *
 */
class DuplicatedBinReportForGeneratedBinsInDataFile extends GeneratedBinForDataFile{
	
	@Override
	protected DataFile processWithSQL(ResultDataFile dataFile,
	Connection connection, Element configuration) {
		
		//we intiialize hibernate cause we need it for this function to work
		initializeHibernate()
		
		Set<Integer> binGenerated = generatedBinsInDataFile(dataFile,connection);		
		
		BinComparisonMatrix matrix = new BinComparisonMatrix()
		DataFile file = matrix.createMatrix(2000,900,binGenerated,connection)
		
		writeObject(file, configuration, "duplicatedBinReport");
		
		
		return null
	}
	
	public String getDescription(){
		return "a report of duplicated bins in this database"
	}
}
