##
# defines neccesaery properties to connect to the old school binbase
# system to query existing targets on demand
#
wcmc:
 workflow:
  gcms:
    library:
      binbase:
        password: c258083
        host: venus.fiehnlab.ucdavis.edu
        instrument: LECO-GC-TOF
        columns:
          - rtx5recal
          - volatile
          - binbasebt