##
# defines neccesaery properties to connect to the old school binbase
# system to query existing targets on demand
#
carrot:
  gcms:
    library:
      binbase:
        columns:
          - rtx5recal
          - volatile