debug: false

spring:
  profiles:
    include:
      - carrot.lcms
      - file.source.eclipse
      - carrot.runner.required
      - carrot.processing.replacement.rtmz
      - carrot.processing.peakdetection
      - carrot.processing.dump
      - carrot.report.quantify.height
      - carrot.targets.yaml.annotation
      - carrot.targets.yaml.correction
      - carrot.resource.store.local
      - carrot.output.writer.txt
      - carrot.nostasis
      - carrot.scheduler.local
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - edu.ucdavis.fiehnlab.ms.carrot.cloud.bucket.BucketStorageConfiguration

---
spring:
  profiles: test
