debug: false

spring:
  profiles:
    include:
      - carrot.lcms
      - file.source.eclipse
      - carrot.runner.required
      - carrot.processing.replacement.rtmz
      - carrot.processing.peakdetection
      - carrot.processing.dump
      - carrot.report.quantify.height
      - carrot.targets.yaml.annotation
      - carrot.targets.yaml.correction
      - carrot.resource.store.local
      - carrot.output.storage.local
      - carrot.nostasis
      - carrot.output.writer.txt

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

---
spring:
  profiles: test
