debug: false

spring:
  profiles:
    active: defaultt
    include:
      - dev
      - jenny
      - carrot.lcms
      - file.source.luna
      - file.source.eclipse
      - carrot.output.storage.aws
      - carrot.resource.loader.bucket
      - carrot.resource.store.bucket
      - carrot.targets.mona
      - carrot.runner.required
      - carrot.processing.replacement.simple
      - carrot.processing.peakdetection
      - carrot.report.quantify.height

stasis:
  baseurl: http://api.metabolomics.us/stasis

mona:
  rest:
    server:
      user: admin
      password: admin
      port: 9090
