debug: false

spring:
  profiles:
    include:
      - carrot.lcms
      - file.source.eclipse
      - carrot.runner.required
      - carrot.processing.replacement.rtmz
      - carrot.processing.peakdetection
      - carrot.processing.dump
      - carrot.report.quantify.height
      - carrot.targets.yaml.annotation
      - carrot.targets.yaml.correction
      - carrot.resource.store.local
      - carrot.output.storage.local
      - carrot.nostasis
      - carrot.output.writer.txt

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

stasis:
  baseurl: http://api.metabolomics.us/stasis

mona:
  rest:
    server:
      host: ipa.fiehnlab.ucdavis.edu
      user: admin
      password: admin
      port: 9090

email:
  host: smtp.gmail.com
  port: 25
  username: binbase@gmail.com
  pass: fiehnlab-2018

---
spring:
  profiles: test

mona:
  rest:
    server:
      host: localhost
      user: admin
      password: admin
      port: 9090

stasis:
  baseurl: http://test-api.metabolomics.us/stasis
