spring:
  profiles:
    active: default
    include:
      - carrot.report.quantify.height
      - carrot.processing.replacement.simple
      - file.source.eclipse


carrot:
  sample:
    name: '${CARROT_SAMPLE}'
  method: '${CARROT_METHOD}'


---

spring:
  profiles:
    active: carrot.binbase
    include:
      - carrot.gcms
      - carrot.gcms.library.binbase

---

spring:
  profiles:
    active: carrot.lcms
    include:
      - carrot.processing.peakdetection