spring:
  profiles:
    active: default
    include:
      - carrot.report.quantify.height
      - carrot.processing.replacement.simple
      - carrot.processing.peakdetection
      - carrot.output.writer.aws
      - carrot.resource.loader.bucket

carrot:
  sample:
    name: '${CARROT_SAMPLE}'
    method: '${CARROT_METHOD}'
