spring:
  main:
    web-application-type: none
  profiles:
    active: default
    include:
      - carrot.report.quantify.height
      - carrot.processing.replacement.simple
      - carrot.processing.peakdetection
      - carrot.output.storage.aws
      - carrot.resource.loader.bucket
      - carrot.resource.store.bucket
      - carrot.runner.required
      - carrot.targets.dynamic
      - carrot.targets.mona

logging:
  level:
    root: WARN

carrot:
  sample: '${CARROT_SAMPLE}'
  method: '${CARROT_METHOD}'
  mode: '${CARROT_MODE:lcms}'


#which email account to use
email:
  host: smtp.gmail.com
  port: 25
  username: binbase@gmail.com
  pass: fiehnlab-2018

mona:
  rest:
    server:
      host: ipa.fiehnlab.ucdavis.edu
      port: 9090
      user: admin
      password: admin

---
spring:
  profiles: test

logging:
  level:
    root: info

mona:
  rest:
    server:
      host: localhost
      port: 9090
      user: admin
      password: admin
