spring:
  main:
    web-application-type: none
  profiles:
    active: default
    include:
      - carrot.report.quantify.height
      - carrot.processing.replacement.mzrt
      - carrot.processing.peakdetection
      - carrot.resource.loader.bucket.data
      - carrot.resource.store.bucket.result
      - carrot.output.writer.json
      - carrot.output.storage.aws
      - carrot.output.storage.converter.target
      - carrot.output.storage.converter.sample
      - carrot.runner.required
      - carrot.targets.yaml.correction
      - carrot.targets.yaml.annotation
      - carrot.email.enable
      - carrot.filters.ioncount
      - carrot.filters.intensity

logging:
  level:
    root: info

carrot:
  sample: '${CARROT_SAMPLE}'
  method: '${CARROT_METHOD}'
  mode: '${CARROT_MODE:lcms}'

mona:
  rest:
    server:
      host: ipa.fiehnlab.ucdavis.edu
      port: 9090

wcmc:
  api:
    mona:
      rest:
        server:
          user: admin
          password: admin
  email:
    host: smtp.gmail.com
    port: 25
    username: binbase@gmail.com
    pass: fiehnlab-2018

---
spring:
  profiles: "test"

wcmc:
  workflow:
    resource:
      store:
        bucket:
          name: "datatest-carrot"
          result: "wcmc-data-stasis-result-test"
