email:
  host: smtp.gmail.com
  port: 25
  username: binbase@gmail.com
  pass: fiehnlab-2018

mona:
  rest:
    server:
      user: admin
      password: admin
      host: localhost
      port: 9090

logging:
  register-shutdown-hook: false

spring:
  cache:
    type: none

---
spring:
  profiles: redis-cache
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

