/*
 * Created on Nov 18, 2005
 */
package edu.ucdavis.genomics.metabolomics.util.statistics;

import edu.ucdavis.genomics.metabolomics.exception.ConfigurationException;
import edu.ucdavis.genomics.metabolomics.util.io.dest.Destination;
import edu.ucdavis.genomics.metabolomics.util.io.source.Source;

/**
 * provides us with the possibility to create statistics on the fly from the given sources to a provides destination
 * @author wohlgemuth
 * @version Nov 18, 2005
 *
 */
public interface StatisticProcessor {
	
	/**
	 * 
	 * @author wohlgemuth
	 * @version Nov 18, 2005
	 * @param rawdata points to some rawdata, generated by the binbase
	 * @param sop poitns to an sop for statistic procedures
	 * @param destination where we wanna save the result
	 * @throws ConfigurationException 
	 */
	public void process(Source rawdata, Source sop, Destination destination) throws ConfigurationException;
}
