carrot:
  lcms:
    correction:
      config:
        - name: lcms_istds
          description: "Internal Standards used in the lab (positive mode)"
          column: test
          ionMode: positive
          instrument: test
          minimumPeakIntensity: 10000
          targets:
            - identifier: 1_CE(22:1) iSTD [M+Chol-head-H2O+H]+_SQHUGNAFKZZXOT-JWTURFAQSA-N
              accurateMass: 1076.0151
              retentionTime: 11.73
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_CE(22:1) iSTD [M+Na]+_SQHUGNAFKZZXOT-JWTURFAQSA-N
              accurateMass: 729.653
              retentionTime: 11.73
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_CE(22:1) iSTD [M+NH4]+_SQHUGNAFKZZXOT-JWTURFAQSA-N
              accurateMass: 724.6985
              retentionTime: 11.73
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_Cer(d18:1/17:0) iSTD [M+H-H2O]+_ICWGMOFDULMCFL-QKSCFGQVSA-N
              accurateMass: 534.5247
              retentionTime: 5.95
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_Cer(d18:1/17:0) iSTD [M+H]+_ICWGMOFDULMCFL-QKSCFGQVSA-N
              accurateMass: 552.5352
              retentionTime: 5.95
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_Cer(d18:1/17:0) iSTD [M+Na]+_ICWGMOFDULMCFL-QKSCFGQVSA-N
              accurateMass: 574.5172
              retentionTime: 5.96
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_Cholesterol d7 iSTD [M-H2O+H]+_HVYWMOMLDIMFJA-IFAPJKRJSA-N
              accurateMass: 376.39599999999996
              retentionTime: 4.78
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_CUDA iSTD [M+H]+_HPTJABJPZMULFH-UHFFFAOYSA-N
              accurateMass: 341.2801
              retentionTime: 0.74
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_DG(12:0/12:0/0:0) iSTD [M+K]+_OQQOAWVKVDAJOI-VWLOTQADSA-N
              accurateMass: 495.3448
              retentionTime: 4.26
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_DG(12:0/12:0/0:0) iSTD [M+Na]+_OQQOAWVKVDAJOI-VWLOTQADSA-N
              accurateMass: 479.3713
              retentionTime: 4.26
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_DG(12:0/12:0/0:0) iSTD [M+NH4]+_OQQOAWVKVDAJOI-VWLOTQADSA-N
              accurateMass: 474.4155
              retentionTime: 4.26
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_DG(18:1/2:0/0:0) iSTD [M+K]+_PWTCCMJTPHCGMS-YRBAHSOBSA-N
              accurateMass: 437.2666
              retentionTime: 3.17
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_DG(18:1/2:0/0:0) iSTD [M+Na]+_PWTCCMJTPHCGMS-YRBAHSOBSA-N
              accurateMass: 421.2928
              retentionTime: 3.16
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_DG(18:1/2:0/0:0) iSTD [M+NH4]+_PWTCCMJTPHCGMS-YRBAHSOBSA-N
              accurateMass: 416.3375
              retentionTime: 3.17
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_LPC(17:0) iSTD [M+H]+_SRRQPVVYXBTRQK-XMMPIXPASA-N
              accurateMass: 510.3565
              retentionTime: 1.8
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_LPE(17:1) iSTD [M+H]+_LNJNONCNASQZOB-HEDKFQSOSA-N
              accurateMass: 466.2929
              retentionTime: 1.27
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_MG (17:0/0:0/0:0) iSTD [M+NH4]+_SVUQHVRAGMNPLW-UHFFFAOYSA-N
              accurateMass: 362.3264
              retentionTime: 3.02
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_MG(17:0/0:0/0:0) iSTD [M+H]+_SVUQHVRAGMNPLW-UHFFFAOYSA-N
              accurateMass: 345.3001
              retentionTime: 3.02
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_MG(17:0/0:0/0:0) iSTD [M+Na]+_SVUQHVRAGMNPLW-UHFFFAOYSA-N
              accurateMass: 367.2821
              retentionTime: 3.02
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_PC(12:0/13:0) iSTD [M+H]+_FCTBVSCBBWKZML-WJOKGBTCSA-N
              accurateMass: 636.4604
              retentionTime: 3.5
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_PE(17:0/17:0) iSTD [M+H]+_YSFFAUPDXKTJMR-DIPNUNPCSA-N
              accurateMass: 720.554
              retentionTime: 6.26
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_SM(d18:1/17:0) iSTD [M+H]+_YMQZQHIESOAPQH-JXGHDCMNSA-N
              accurateMass: 717.5907
              retentionTime: 5.04
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_Sphingosine(d17:1) iSTD [M+H]+_RBEJCQPPFCKTRZ-LHMZYYNSSA-N
              accurateMass: 286.2742
              retentionTime: 0.98
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_TAG d5(17:0/17:1/17:0) iSTD [M+Na]+_OWYYELCHNALRQZ-ADIIQMQPSA-N
              accurateMass: 874.7887
              retentionTime: 11.02
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
            - identifier: 1_TAG d5(17:0/17:1/17:0) iSTD [M+NH4]+_OWYYELCHNALRQZ-ADIIQMQPSA-N
              accurateMass: 869.8333
              retentionTime: 11.02
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: false
              confirmed: true
        - name: lcms_istds
          column: test
          ionMode: negative
          instrument: test
          minimumPeakIntensity: 10000
          description: "Internal Standards used in the lab (negative mode)"
          targets:
            - identifier: "1_ISTD CUDA [M-H]-"
              accurateMass: 339.26
              retentionTime: 0.66
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD LPE (17:1) [M-H]-"
              accurateMass: 464.28
              retentionTime: 1.43
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD LPC (17:0) [M+HAc-H]-"
              accurateMass: 568.36
              retentionTime: 1.912
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD FA (16:0)-d3 [M-H]-"
              accurateMass: 258.25
              retentionTime: 2.49
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD MAG (17:0/0:0/0:0) [M+HAc-H]-"
              accurateMass: 403.31
              retentionTime: 3.135
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD PC (12:0/13:0) [M+HAc-H]-"
              accurateMass: 694.47
              retentionTime: 3.61
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD PG (17:0/17:0) [M-H]-"
              accurateMass: 749.53
              retentionTime: 5.148
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD SM (d18:1/17:0) [M+HAc-H]-"
              accurateMass: 775.6
              retentionTime: 5.199
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD Ceramide (d18:1/17:0) [M+HAc-H]-"
              accurateMass: 610.54
              retentionTime: 6.106
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD Ceramide (d18:1/17:0) [M+Cl]-"
              accurateMass: 586.5
              retentionTime: 6.114
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
            - identifier: "1_ISTD PE (17:0/17:0) [M-H]-"
              accurateMass: 718.54
              retentionTime: 6.422
              retentionTimeUnit: minutes
              isInternalStandard: true
              requiredForCorrection: true
              confirmed: true
