msdial:
  connectTimeoutMillis: 250
  readTimeoutMillis: 250000

spectrum:
  minimizer:
    basePeakRatio: 0.0001

carrot:
  targets:
    yaml:
      properties:
        resource: "libraries.yml"
spring:
  cache:
    type: none

---
spring:
  profiles: redis-cache
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

---
spring:
  profiles: "carrot.resource.loader.bucket"

carrot:
  targets:
    yaml:
      properties:
        resource: "libraries.yaml"
