spring:
  profiles:
    active: default
    include:
      - prod
      - carrot.gcms
      - carrot.lcms
      - carrot.output.storage.aws
      - carrot.resource.loader.bucket
      - carrot.resource.store.bucket
      - carrot.targets.mona
      - carrot.scheduler.aws
      - carrot.gcms.library.binbase
      - file.source.luna
      - file.source.eclipse

  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

server:
  port: 18080

#which email account to use
email:
  host: smtp.gmail.com
  port: 25
  username: binbase@gmail.com
  pass: fiehnlab-2018

# mona server to run against
mona:
  rest:
    server:
      user: admin
      password: admin
      host: localhost
      port: 9090
