server:
  port: 18080

#which email account to use
email:
  host: smtp.gmail.com
  port: 25
  username: binbase@gmail.com
  pass: fiehnlab-2018

spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

# mona server to run against
mona:
  rest:
    server:
      user: admin
      password: admin
      host: ipa.fiehnlab.ucdavis.edu
      port: 9090
