debug: true

spring:
  profiles:
    active: dev
    include:
#      - file.source.luna
#      - file.source.eclipse
      - carrot.lcms
      - carrot.output.storage.aws
      - carrot.resource.loader.bucket
      - carrot.resource.store.bucket
      - carrot.targets.mona
#      - carrot.gcms.library.binbase
      - carrot.scheduler.local
      - carrot.runner.required
      - carrot.processing.replacement.simple
      - carrot.processing.peakdetection
      - carrot.report.quantify.height


stasis:
  baseurl: https://dev-api.metabolomics.us/stasis
