spring:
  profiles:
    active: default
    include:
      - prod
      - file.source.luna
      - file.source.eclipse
      - carrot.gcms
      - carrot.lcms
      - carrot.output.storage.aws
      - carrot.resource.loader.bucket
      - carrot.resource.store.bucket
      - carrot.targets.mona
      - carrot.scheduler.aws
      - carrot.gcms.library.binbase
      - carrot.runner.required

stasis:
  baseurl: http://api.metabolomics.us/stasis
