spring:
  profiles:
    active: dev
    include:
      - file.source.luna
      - file.source.eclipse
      - carrot.lcms
      - carrot.targets.mona
      - carrot.target.dynamic
      - carrot.output.storage.aws
      - carrot.processing.replacement.simple
      - carrot.processing.peakdetection
      - carrot.report.quantify.height
      - carrot.resource.loader.bucket
      - carrot.resource.store.bucket
      - carrot.scheduler.aws
#      - carrot.store.result.fserv4j
#      - carrot.output.writer.flat

#which rabbit mq to use
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#which mona server to use
mona:
  rest:
    server:
      user: admin
      password: admin
      host: localhost
      port: 9090

wcmc:
  pipeline:
    workflow:
      config:
        correction:
          minimumFoundStandards: 10
          regression:
            polynom: 3
