debug: false

spring:
  profiles:
    active: prod
    include:
      - carrot.lcms
      - carrot.nostasis
      - file.source.eclipse
      - carrot.runner.required
#      - carrot.processing.replacement.simple
      - carrot.processing.peakdetection
      - carrot.report.quantify.height
      - carrot.output.storage.local
      - carrot.output.writer.txt
      - carrot.targets.yaml.correction
      - carrot.targets.yaml.annotation
      - carrot.email.enable
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
wcmc:
  email:
    host: smtp.gmail.com
    port: 25
    username: binbase@gmail.com
    pass: fiehnlab-2018
