logging:
  level:
    root: info

carrot:
  targets:
    yaml:
      properties:
          resource: "libraries.yml"

---
spring:
  profiles: "carrot.resource.loader.bucket"

carrot:
  targets:
    yaml:
      properties:
          resource: "libraries.yaml"

wcmc:
  workflow:
    resource:
      store:
        bucket:
          name: "carrot-libraries"
