logging:
  level:
    root: info

carrot:
  targets:
    yaml:
      properties:
          resource: "libraries.yml"

---
spring:
  profiles: "carrot.resource.loader.bucket.data"

carrot:
  targets:
    yaml:
      properties:
          resource: "libraries.yaml"
