spring:
  profiles:
    active:  carrot.targets.mona, carrot.target.dynamic, carrot.report.quantify.height, carrot.store.result.fserv4j, carrot.output.writer.txt, carrot.processing.replacement.simple
  http:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  rabbitmq:
    host: blonde.fiehnlab.ucdavis.edu
    port: 5673
    username: rabbituser
    password: rabbitpass

mona:
  rest:
    server:
      user: admin
      password: admin
      host: trashcan.fiehnlab.ucdavis.edu
      port: 80

server:
  port: 18080

email:
  host: smtp.gmail.com
  port: 25
  username: binbase@gmail.com
  pass: password
wcmc:
  api:
    rest:
      msdialrest4j:
        host: luna.fiehnlab.ucdavis.edu
        port: 8080
