spring:
  profiles:
    active:  carrot.targets.mona, carrot.target.dynamic, carrot.report.quantify.height, carrot.store.result.fserv4j, carrot.output.writer.flat, carrot.processing.replacement.simple, carrot.processing.peakdetection, carrot.lcms
  http:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

#which rabbit mq to use
  rabbitmq:
    host: blonde.fiehnlab.ucdavis.edu
    port: 5673
    username: rabbituser
    password: rabbitpass

#which mona server to use
mona:
  rest:
    server:
      user: admin
      password: admin
      host: megamona.fiehnlab.ucdavis.edu
      port: 80

server:
  port: 18080

#which email account to use
email:
  host: smtp.gmail.com
  port: 25
  username: binbase@gmail.com
  pass: BinBase2018

#which rest backend to use
wcmc:
  api:
    rest:
      msdialrest4j:
        host: phobos.fiehnlab.ucdavis.edu
        port: 8080

#which redis server to use for
