spring:
  profiles:
    active: carrot.scheduler.local, carrot.targets.mona, carrot.target.dynamic, carrot.report.quantify.height, carrot.store.result.fserv4j, carrot.output.writer.txt, carrot.processing.replacement.simple
  http:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

mona:
  rest:
    server:
      user: admin
      password: admin
      host: 127.0.0.1
      port: 80

server:
  port: 18080
